name: Convert

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    name: Convert and push
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
      - name: Install obsidian-export
        run: cargo install obsidian-export
      - name: Convert
        run: |
          mkdir ../convert
          obsidian-export . ../convert      
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: master
          FOLDER: ../convert
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Converted ${{ github.sha }}"
